Update expected AdmissionReview
        --- FAIL: TestCompatibility/admission.k8s.io.v1beta1.AdmissionReview/v1.14.0 (0.02s)
            compatibility.go:460: json differs
            compatibility.go:461:   strings.Join({
                  	... // 31 identical lines
                  	`    "object": {"apiVersion":"example.com/v1","kind":"CustomType","spec":{"replicas":1},"status":{"available":1}},`,
                  	`    "oldObject": {"apiVersion":"example.com/v1","kind":"CustomType","spec":{"replicas":1},"status":{"available":1}},`,
                - 	`    "dryRun": true`,
                + 	`    "dryRun": true,`,
                + 	`    "options": null`,
                  	"  },",
                  	`  "response": {`,
                  	... // 33 identical lines
                  }, "\n")

            compatibility.go:466: yaml differs
            compatibility.go:467:   strings.Join({
                  	... // 23 identical lines
                  	"      available: 1",
                  	"  operation: 祈¡ıŵDz廔ȇ{sŊƏp饏姥呄鐊",
                + 	"  options: null",
                  	"  resource:",
                  	`    group: "5"`,
                  	... // 38 identical lines
                  }, "\n")

            compatibility.go:472: proto differs
            compatibility.go:474:   strings.Join({
                  	... // 37 identical lines
                  	"    }",
                  	"    11: 1",
                + 	`    12: ""`,
                + 	`    15: ""`,
                  	"  }",
                  	"  2 {",
                  	... // 36 identical lines
                  }, "\n")

Null `options` in json and additional proto tag 12 caused by https://github.com/kubernetes/kubernetes/pull/77563#discussion_r282803268

Proto tag 15 caused by https://github.com/kubernetes/kubernetes/pull/78135/files#diff-3bc4acaf71b6b50648da046287017c54R82

Kubernetes-commit: fcea91c1650b23ec07a96b5a62d08466a3771f29